### ISSUE TITLE
how to show banner ad at top

### ISSUE THREAD

**Issue by android-rk** [pubnative/pubnative-android-mediation-sdk#1]
right now in mediation sample banner ad is loading at bottom. Is there any flag to show on top.
mBanner.load(Context ctx,String appToken,String placementName);
here no option for Banner position.

**Comment by psychocandy** [comment]
@android-rk thank you for raising this issue and sorry for not replying sooner.

We do plan to support this on our next versions. We have simplified the usage on our upcoming version (currently in beta), and we will support mBanner as part of our Small layouts (scheduled to be released next month).
